$bg0 = 2e3440,
$bg1 = 3b4252,
$bg2 = 434c5e,
$bg3 = 4c566a,

$fg = eceff4,

$red = bf616a,
$orange = d08770,
$yellow = ebcb8b,
$green = a3be8c,
$aqua = 88c0d0,
$blue = 5e81ac,
$purple = b48ead,
$pink = d48ead,

$grey0 = d8dee9,
$grey1 = e5e9f0,

$accent = 88c0d0
