# vim:ft=kitty

## name: xyrn's nord
## author: xyrn
## license: MIT

cursor                  #eceff4
cursor_text_color       #2e3440

foreground              #eceff4
background              #2e3440
selection_foreground    #d8dee9
selection_background    #4c566a

url_color               #5e81ac

scrollbar_handle_color  #eceff4
scrollbar_track_color   #2e3440

wayland_title_bar       system
macos_title_bar         system

active_tab_foreground   #eceff4
active_tab_background   #3b4252
inactive_tab_foreground #e5e9f0
inactive_tab_background #2e3440
tab_bar_background      #2e3440

# black
color0  #3b4252
color8  #4c566a

# red
color1  #bf616a
color9  #bf616a

# green
color2  #a3be8c
color10 #a3be8c

# yellow
color3  #ebcb8b
color11 #ebcb8b

# blue
color4  #5e81ac
color12 #5e81ac

# magenta
color5  #b48ead
color13 #b48ead

# cyan
color6  #88c0d0
color14 #88c0d0

# white
color7  #d8dee9
color15 #e5e9f0
