# vim:ft=kitty

## name: vaporwave
## author: xyrn
## license: MIT

cursor                  #c4631f
cursor_text_color       #0b0811

foreground              #f4e5bc
background              #190d23
selection_foreground    #190d23
selection_background    #61f0ff

url_color               #2831b2

scrollbar_handle_color  #ab8e88
scrollbar_track_color   #0b0811

wayland_title_bar       system
macos_title_bar         system

active_tab_foreground   #f4e5bc
active_tab_background   #190d23
inactive_tab_foreground #d2b9b4
inactive_tab_background #0b0811
tab_bar_background      #0b0811

# black
color0  #0b0811
color8  #63173e

# red
color1  #82222d
color9  #82222d

# green
color2  #65bf8c
color10 #65bf8c

# yellow
color3  #daae41
color11 #daae41

# blue
color4  #2831b2
color12 #2831b2

# magenta
color5  #bf65bd
color13 #bf65bd

# cyan
color6  #61f0ff
color14 #61f0ff

# white
color7  #ab8e88
color15 #d2b9b4
